name: openet-lib-test-action

# Run the tests only if code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  test-runner:
    name: OpenET Test Runner
    # Only tested on Ubuntu 24 and Windows 11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Read repo secret for stress tests and save into .env file
      shell: bash
      env:
        ET_KEY: ${{ secrets.ET_KEY }}
      run: echo "ET_KEY=$ET_KEY" >> .env
    # Install venv-run to easily run a virtualenv
    - name: virtualenv setup
      run: |
        pip install venv-run
        python -m venv .
        venv-run pip install -r requirements.txt
    - name: Run Tests
      run: venv-run -m pytest --cov
